title: "Introduction to Programming with Python"
repository:
  url: https://github.com/luketudge/introduction-to-programming
html:
  use_repository_button: true
  use_issues_button: true
execute:
  exclude_patterns: [types.ipynb, functions.ipynb, databases.ipynb]
sphinx:
  config:
    myst_heading_anchors: 2
