title: "Introduction to Programming with Python"
author: LT
exclude_patterns: ["**/README.md", "**/.pytest_cache/*"]
execute:
  exclude_patterns: [examples/*.py, types.ipynb, functions.ipynb, databases.ipynb]
parse:
  myst_enable_extensions: [colon_fence, dollarmath, substitution]
html:
  use_repository_button: true
  use_issues_button: true
launch_buttons:
  binderhub_url: https://mybinder.org
  colab_url: https://colab.research.google.com
  thebe: true
repository:
  url: https://github.com/luketudge/introduction-to-programming
  path_to_book: content
sphinx:
  config:
    myst_heading_anchors: 4
    nb_custom_formats:
        .py:
            - jupytext.reads
            - fmt: py
